services:
  fastapi_app:
    build: .
    container_name: fastapi_server
    expose:
      - "8000" # 仅对内部网络开放

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80" # 对外暴露 80 端口
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi_app